### ISSUE TITLE
Games listing + game detail - Location info

### ISSUE THREAD

**Issue by CamilleLetang** [Games-of-Switzerland/swissgamesgarden#51]
https://docs.google.com/spreadsheets/d/1pWOGpADxvNEWcYnpTFpCyhS9rtIjCYgIdZmBppDkC2Q/edit#gid=1947116134
On the listing use only "Studio Canton" as filter
On the game detail display only "Studio Location"

@WengerK please verify in the database if you use the both fields.

Reminder: we decided to use canton in the filters because displaying every little cities isn't very relevant here

# tasks

- [x] Add Field Canton(s) to games
- [x] Migrate update this data
- [x] Add Cantons to Elasticearch
- [x] Add Cantons to JSON:API
- [x] Allow Filtering on Cantons Elasticsearch
- [x] Add Cantons Facets on Elasticsearch
- [x] Run migration on Prod
- [x] Add Filter on Canton (listing of games) instead of Cities (locations)
- [x] On game detail page display Canton and Cities (locations)

**Comment by WengerK** [comment]
Indeed Game canton has not been migrated.

We should:
- Add Field Canton(s) to games
- Migrate update this data
- Add Cantons to Elasticearch
- Add Cantons to JSON:API
- Allow Filtering on Cantons Elasticsearch
- Add Cantons Facets on Elasticsearch

**Comment by WengerK** [comment]
Run migration with

```

**Comment by WengerK** [comment]
ce n'est pas encore visible en frontend. car avant on avait pas ce champ et cette facet (canton) donc à ajuster @tonifisler

**Comment by WengerK** [comment]
added both filters & detail list

<img width="1904" alt="Screenshot 2022-09-10 at 17 07 49" src="https://user-images.githubusercontent.com/1841592/189489460-e6f66ed4-1d3c-459d-95cc-099167e8cc44.png">


<img width="642" alt="Screenshot 2022-09-10 at 17 06 17" src="https://user-images.githubusercontent.com/1841592/189489450-c2afebcd-8dba-4e3c-b853-a50f0dc3843e.png">
